
  CREATE TABLE "INSA"."INSA_COM" 
   (	"GUBUN" VARCHAR2(100 BYTE), 
	"CODE" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"NOTE" VARCHAR2(100 BYTE), 
	 CONSTRAINT "INSACOM_GUBCODE_PK" PRIMARY KEY ("GUBUN", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  CREATE TABLE "INSA"."INSA" 
   (	"SABUN" NUMBER, 
	"JOIN_DAY" DATE, 
	"RETIRE_DAY" DATE, 
	"PUT_YN" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE) CONSTRAINT "INS_NAME_NN" NOT NULL ENABLE, 
	"REG_NO" VARCHAR2(100 BYTE) CONSTRAINT "INS_REGNO_NN" NOT NULL ENABLE, 
	"ENG_NAME" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"HP" VARCHAR2(100 BYTE) CONSTRAINT "INS_HPNO_NN" NOT NULL ENABLE, 
	"POS_GBN_CODE" VARCHAR2(100 BYTE), 
	"CMP_REG_NO" VARCHAR2(100 BYTE), 
	"CMP_REG_IMAGE" VARCHAR2(100 BYTE), 
	"SEX" VARCHAR2(100 BYTE), 
	"YEARS" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ZIP" VARCHAR2(100 BYTE), 
	"ADDR1" VARCHAR2(100 BYTE), 
	"ADDR2" VARCHAR2(100 BYTE), 
	"DEPT_CODE" VARCHAR2(100 BYTE), 
	"JOIN_GBN_CODE" VARCHAR2(100 BYTE), 
	"ID" VARCHAR2(100 BYTE) CONSTRAINT "INS_ID_NN" NOT NULL ENABLE, 
	"PWD" VARCHAR2(100 BYTE) CONSTRAINT "INS_PW_NN" NOT NULL ENABLE, 
	"SALARY" NUMBER, 
	"KOSA_REG_YN" VARCHAR2(100 BYTE), 
	"KOSA_CLASS_CODE" VARCHAR2(100 BYTE), 
	"MIL_YN" VARCHAR2(100 BYTE), 
	"MIL_TYPE" VARCHAR2(100 BYTE), 
	"MIL_LEVEL" VARCHAR2(100 BYTE), 
	"MIL_STARTDATE" DATE, 
	"MIL_ENDDATE" DATE, 
	"JOB_TYPE" VARCHAR2(100 BYTE), 
	"GART_LEVEL" VARCHAR2(100 BYTE), 
	"SELF_INTRO" CLOB, 
	"CRM_NAME" VARCHAR2(100 BYTE), 
	"PROFILE" VARCHAR2(100 BYTE), 
	"RESUME" VARCHAR2(100 BYTE), 
	"CURRENT_YN" VARCHAR2(100 BYTE), 
	 CONSTRAINT "INS_NO_PK" PRIMARY KEY ("SABUN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SELF_INTRO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

